### PR TITLE
Diagram updates

### PR DESCRIPTION
**Pull request by marissaeinhorn**

### CODE REVIEW

**Comment by marissaeinhorn** [comment]
If you cant view the diagrams in github: https://drive.google.com/drive/folders/1GHsQX0H3KKkwULU1MY6DVVw8uzv8rTEA?usp=sharing

**Comment by Donovan-Medina** [comment]
The range.drawio diagram makes sense to me with the relationship of each service/component in this overarching environment. I'd wish I'd be able to see the difference between this version and the previous -- perhaps saving both the drawio file and an exported png/jpg would help in the future when modifying the diagram. We will most definitely talk over the issues and tasks next week, but one food for thought I don't see in this diagram is if we would utilize GitLab's container registry or some method of storing pre-made images. Is the current route to only use the HCL templates with ISOs to build images with Packer every time a new range is deployed, then use snapshots?

**Comment by marissaeinhorn** [comment]
Packer images are only built once and then stored in the vcenter datastore.  They only get rebuilt when updates are made to the image not every time a new class is started.  I dont have a good way to indicate that on the diagram but if you have any ideas let me know.

Current versions of these diagrams are on the home page of the wiki

**Comment by Donovan-Medina** [comment]
Thank you I see the changes now -- they look good. Storing the images in the vCenter datastore makes total sense and I can see how it would be weird to indicate that specifically in this diagram. It seems like this diagram is specific to the workflow of starting from scratch or when an update is made. Maybe we can delineate between the workflow of initializing the vCenter with newly created packer images, and one with using what's stored in vCenter. IDK -- I'm just spitballing.

**Review by Donovan-Medina — APPROVED** [review]
Looks good to me. I can see what the interactions are supposed to be from the instructorExperience as well as the range.drawio.

**Review by Timo604 — APPROVED** [review]
Looks good to me

**Comment by rylagek** [comment]
@marissaeinhorn A couple small things
1. `text` is sitting in the middle of the instructor experience diagram 
2. In the range diagram, we should update the example file extensions to the proper values:
- Packer.json -> Packer.pkr.hcl
- Terraform.cfg -> Terraform.tf

**Comment by marissaeinhorn** [comment]
Updated docs are in this folder https://drive.google.com/drive/folders/1GHsQX0H3KKkwULU1MY6DVVw8uzv8rTEA?usp=sharing

**Pull request merged**
