### PR TITLE
#237 converted services to utilize environment variables

### PR DESCRIPTION
**Pull request by Donovan-Medina**
Changes: 
- [dotenv ](https://pypi.org/project/python-dotenv/)(python now reads environment variables from .env)
- [black ](https://black.readthedocs.io/en/stable/)(I recommend devs utilize python -m black <file.py> to automatically format python files according to PEP8 standard)

- README
New devs/users of the micro services (gitea, semaphore, jenkins, etc) will need to pip install -r requirements.txt to ensure python modules are installed

- converted additional items such as ports to environment variables

### CODE REVIEW

**Comment by Donovan-Medina** [comment]
Adding a task in the "parking-lot" for the idea of automating the .env creation and python dotenv pip installation via setup.sh.
- sudo apt-get install python3 && python3-dev
- pip install -r /home/control/vater/requirements/requirements.txt

We should also delineate between dev requirements and production requirements.
Dev requirements would utilize the production dependencies like dotenv, but also formatters like black, flake8 and some pre-commit conditions.

For now, I'm updating the wiki.

**Comment by Donovan-Medina** [comment]
Automated pip installation and env configuration from setup.sh

**Comment by marissaeinhorn** [comment]
Were using VATER as a stable but interim solution before we move to the RANS.  Given the timeline of ~6 months before we move content I dont think we should put in the work to split dev vs production installations of control

**Comment by marissaeinhorn** [comment]
Tested and gitea looks good.  Well test with semaphore once we get the docker container fixed

**Comment by marissaeinhorn** [comment]
Closes #247 
Closes #246

**Review by dev4vater — APPROVED** [review]

**Comment by Donovan-Medina** [comment]
Incorporated Terraform .tfvars and Semaphore's creds.yml to be created by setup.sh.
No more hardcoded credentials or secrets will be pushed up to github.

**Pull request merged**
